include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
    lines_longer_than_80_chars: false
    use_string_buffers: false
    unnecessary_getters_setters: false
    omit_local_variable_types: false
    prefer_final_locals: false
    prefer_final_in_for_each: false
